on: [push]
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install flake8
        run: pip install flake8 pylint
      - name: Run flake8
        run: flake8 guess_where_telegram_bot.py --ignore=E501
      - name: Run pylint
        run: pylint guess_where_telegram_bot.py --disable=C0301,C0114,C0116,E0401
